### ISSUE TITLE
JsHint broke on Sublime Text 2

### ISSUE THREAD

**Issue by lifeinafolder** [uipoet/sublime-jshint#33]
Error I am getting on build:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module './../lib/cli'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jshint/bin/hint:2:1)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
[Finished in 0.1s with exit code 1]
```

**Comment by YoEugene** [comment]
In my case, I found the real problem is not in `JSHint.sublime-build` file but in `JSHint.py` file

So the steps are:
1. Go the your JSHint Folder
(For me is: `~/Library/Application Support/Sublime Text 3/Packages/JSHint`)
2. open the `JSHint.py` file inside it
3. Go to terminal, and enter `which jshint` to get your path of `jshint` command
(For me is: `/Users/yoeugene/nvm/v0.10.35/bin/jshint`)
4. Cope the above string before `/jshint`, and paste it to `JSHint.py` in the `args['path']` part
(*Notice there is no `/jshint` in the path I paste*)
![2015-09-26 10 14 58](https://cloud.githubusercontent.com/assets/7090876/10117960/dcd310f8-649b-11e5-8149-23323fe3e35d.png)
5. Save the file and that's it!!  Try again `Ctrl+J` or `Alt+J` on your JS file and see if it's working.

**Comment by yurychika** [comment]
@YoEugene 
Thanks! It really works perfectly.

**Comment by jshamley** [comment]
Thanks @YoEugene, worked like a charm

**Comment by jaywang12** [comment]
@YoEugene: thanks, this works
